name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Checkout repo
        uses: actions/checkout@v4
      -
        name: Parse version
        run: echo "VERSION=$(cat src/NeuXtalViz/_version.py | grep "__version__ =" | head -n 1 | awk '{ print $3 }' | tr -d '"' | cut -f1 -d '+')" >> $GITHUB_ENV
      -
        name: Check image already exists
        run: if [ -n "$(docker manifest inspect ghcr.io/${{ github.repository_owner }}/neuxtalviz:${{ env.VERSION }})" ]; then echo "Image already exists, update the version and try again." && exit 1; fi
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: dockerfiles/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/neuxtalviz:latest,ghcr.io/${{ github.repository_owner }}/neuxtalviz:${{ env.VERSION }}
